service: new-employee-portal-app
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employeeTable}
custom:
  employeeTable: new-employee-table-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
    #Create Experience Details      
  empPortal:
    handler: api.employeeDetails
    name: api
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: createEmpDetails
          method: POST
          cors: true
      - http:
          path: updateEmpDetails/{employeeId}
          method: PUT
          cors: true
      - http:
          path: getEmpDetails/{employeeId}
          method: GET
          cors: true
      - http:
          path: getAllEmpDetails
          method: GET
          cors: true
      - http:
          path: deleteEmpDetails/{employeeId}
          method: DELETE
          cors: true
      - http:
          path: softDeleteEmpDetails/{employeeId}
          method: DELETE
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
          - "dynamodb:DeleteItem"
        Resource:
          - !GetAtt EmployeeTable.Arn

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTable}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: N
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
